FROM python:3.8.6

WORKDIR /opt/app

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -yq --no-install-recommends iptables && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install pipenv

COPY Pipfile /opt/app
COPY Pipfile.lock /opt/app

RUN pipenv sync

COPY . /opt/app

ENTRYPOINT ./entrypoint-native.sh

